# Generated by Django 5.1.1 on 2024-09-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='key',
            field=models.CharField(default='xxxxx', max_length=155),
        ),
    ]
